library(dplyr)      # data manipulation and dataframe processing
library(readr)      # reading tab-delimited files
library(stringr)    # string manipulation
library(ggplot2)    # plotting


##### define directories #####

# directory containing Bash inputs that is also needed here
bash_data <- "bash_data"

# directory containing Bash outputs
bash_dir <- "bash_results"

# directory for R outputs
output_dir <- "r_results"

dir.create(output_dir, showWarnings = FALSE)

##### read ANNOVAR annotation #####
annotation <- read_tsv(
  file.path(
    bash_data,
    "fdr_outliers_annotated.fsj_multianno.txt"
  ),
  show_col_types = FALSE
)


##### identify nonsynonymous SNPs #####

nonsyn_annotation <- annotation %>%
  filter(ExonicFunc.refGene == "nonsynonymous SNV") %>%
  mutate(
    snp = paste(Chr, Start, sep = ":"),
    
    gene_id = str_split(
      AAChange.refGene,
      ":",
      simplify = TRUE
    )[, 1],
    
    aa_change = str_split(
      AAChange.refGene,
      ":",
      simplify = TRUE
    )[, 5],
    
    snp_label = paste(
      gene_id,
      aa_change
    )
  ) %>%
  select(
    snp,
    gene_id,
    aa_change,
    snp_label
  )


##### create candidate-gene summary #####

# Summarize nonsynonymous SNPs and start-loss variants by gene
candidate_genes <- annotation %>%
  filter(Func.refGene == "exonic") %>%
  mutate(
    Gene_symbol = str_split(
      AAChange.refGene,
      ":",
      simplify = TRUE
    )[, 2]
  ) %>%
  group_by(
    Gene.refGene,
    Gene_symbol
  ) %>%
  summarise(
    n_nonsyn = sum(
      ExonicFunc.refGene == "nonsynonymous SNV"
    ),
    
    n_startloss = sum(
      ExonicFunc.refGene == "startloss"
    ),
    
    positions = paste(
      paste0(Chr, ":", Start),
      collapse = "; "
    ),
    
    aa_changes = paste(
      AAChange.refGene,
      collapse = "; "
    ),
    
    .groups = "drop"
  ) %>%
  filter(
    n_nonsyn > 0 |
      n_startloss > 0
  ) %>%
  arrange(desc(n_nonsyn))

write.csv(
  candidate_genes,
  file.path(
    output_dir,
    "candidate_genes_table.csv"
  ),
  row.names = FALSE
)


##### read cluster allele frequencies #####

# Generated by nonsynonymous_snp_frequencies.sh
frequency_data <- read_tsv(
  file.path(
    bash_dir,
    "all_pop_freq.txt"
  ),
  show_col_types = FALSE
)

# separate allele and frequency information 
frequency_data <- frequency_data %>%
  mutate(
    ref_allele = str_split(
      ALLELE1,
      ":",
      simplify = TRUE
    )[, 1],
    
    ref_freq = as.numeric(
      str_split(
        ALLELE1,
        ":",
        simplify = TRUE
      )[, 2]
    ),
    
    alt_allele = str_split(
      ALLELE2,
      ":",
      simplify = TRUE
    )[, 1],
    
    alt_freq = as.numeric(
      str_split(
        ALLELE2,
        ":",
        simplify = TRUE
      )[, 2]
    ),
    
    snp = paste(
      CHROM,
      POS,
      sep = ":"
    )
  )

# combine allele frequencies with SNP annotation
plot_df <- frequency_data %>%
  left_join(
    nonsyn_annotation,
    by = "snp"
  )


##### define genetic cluster names #####

# Change these recoding values since the cluster names generated
# by the Bash script are different.
plot_df <- plot_df %>%
  mutate(
    cluster = recode(
      cluster,
      "archbold" = "Archbold",
      "cbc" = "CBC",
      "sbc" = "SBC",
      "ocala" = "Ocala",
      "merritt" = "Merritt Island",
      "sl" = "SL"
    )
  )


# define genetic cluster order
plot_df$cluster <- factor(
  plot_df$cluster,
  levels = c(
    "Merritt Island",
    "SL",
    "CBC",
    "SBC",
    "Archbold",
    "Ocala"
  )
)

# define genetic cluster colors
cluster_colors <- c(
  "Merritt Island" = "#d62728",
  "SL" = "royalblue1",
  "CBC" = "navy",
  "SBC" = "chartreuse3",
  "Archbold" = "mediumorchid4",
  "Ocala" = "darkorange"
)


##### gene ID to gene-symbol mapping #####

gene_map <- c(
  "g17528" = "g17528.t1",
  "g11583" = "Mast1",
  "g11593" = "MRPL4",
  "g11612" = "WIZ",
  "g11650" = "Efcc1",
  "g11669" = "g11669.t1",
  "g11706" = "TRPT1",
  "g11719" = "WDR74",
  "g11761" = "Bad",
  "g11772" = "Polr1g",
  "g15250" = "ESYT3",
  "g17391" = "PABPN1",
  "g17409" = "Abhd16a",
  "g17432" = "NAA38",
  "g17440" = "SCN1B",
  "g17485" = "Slc5a2",
  "g17490" = "CLN3",
  "g17510" = "slc39a7",
  "g17603" = "TUFM",
  "g17627" = "Ttn",
  "g17637" = "Hgh1",
  "g17762" = "MED11",
  "g17964" = "Dmbt1",
  "g2935"  = "PCDHGB5",
  "g4446"  = "tbc1d24",
  "g8182"  = "SEMA4C",
  "g8188"  = "IL1RN",
  "g8596"  = "BUD13",
  "g8769"  = "g8769.t1",
  "g9552"  = "g9552",
  "g9558"  = "g9558",
  "g9874"  = "USHBP1",
  "g9986"  = "KIF5A",
  "g11766" = "zfpl1",
  "g12909" = "Ammecr1"
)

# add gene symbols
plot_df <- plot_df %>%
  mutate(
    gene_symbol = unname(
      gene_map[gene_id]
    )
  )

# add signs to selected genes
plot_df <- plot_df %>%
  mutate(
    gene_label = case_when(
      
      gene_symbol %in% c(
        "Mast1",
        "CLN3",
        "PCDHGB5",
        "tbc1d24",
        "SEMA4C",
        "KIF5A"
      ) ~ paste0(gene_symbol, " ⬤"),
      
      gene_symbol %in% c(
        "Bad",
        "NAA38"
      ) ~ paste0(gene_symbol, " ⬛"),
      
      gene_symbol %in% c(
        "Polr1g",
        "Abhd16a",
        "slc39a7",
        "Dmbt1",
        "IL1RN",
        "g9552",
        "g9558"
      ) ~ paste0(gene_symbol, " ⬥"),
      
      gene_symbol %in% c(
        "SCN1B",
        "Ttn",
        "USHBP1"
      ) ~ paste0(gene_symbol, " ▲"),
      
      gene_symbol %in% c(
        "ESYT3",
        "Slc5a2"
      ) ~ paste0(gene_symbol, " ⬤"),
      
      TRUE ~ gene_symbol
    )
  )

# define gene order
gene_order <- c(
  
  "Mast1 ⬤",
  "CLN3 ⬤",
  "PCDHGB5 ⬤",
  "tbc1d24 ⬤",
  "SEMA4C ⬤",
  "KIF5A ⬤",
  
  "Bad ⬛",
  "NAA38 ⬛",
  
  "Polr1g ⬥",
  "Abhd16a ⬥",
  "slc39a7 ⬥",
  "Dmbt1 ⬥",
  "IL1RN ⬥",
  "g9552 ⬥",
  "g9558 ⬥",
  
  "SCN1B ▲",
  "Ttn ▲",
  "USHBP1 ▲",
  
  "ESYT3 ⬤",
  "Slc5a2 ⬤"
)

# Add genes not included in the manually defined order
# after the specified genes.
remaining_genes <- setdiff(
  unique(plot_df$gene_label),
  gene_order
)

plot_df$gene_label <- factor(
  plot_df$gene_label,
  levels = c(
    gene_order,
    remaining_genes
  )
)

# save gene and SNP frequency table
frequency_table <- plot_df %>%
  select(
    gene_id,
    gene_symbol,
    snp,
    aa_change,
    cluster,
    ref_allele,
    ref_freq,
    alt_allele,
    alt_freq
  ) %>%
  arrange(
    gene_symbol,
    snp,
    cluster
  )

write.csv(
  frequency_table,
  file.path(
    output_dir,
    "gene_snp_frequencies.csv"
  ),
  row.names = FALSE
)


##### identify gene presence among genetic clusters #####

# A gene is considered present in a genetic cluster when the
# alternate allele frequency is greater than zero.
gene_presence <- plot_df %>%
  filter(
    alt_freq > 0,
    !is.na(gene_symbol)
  ) %>%
  distinct(
    gene_symbol,
    cluster
  )

# count genetic clusters containing each gene
gene_counts <- gene_presence %>%
  group_by(gene_symbol) %>%
  summarise(
    n_clusters = n_distinct(cluster),
    
    clusters = paste(
      sort(unique(cluster)),
      collapse = ", "
    ),
    
    .groups = "drop"
  )

# Genes present in one genetic cluster
genes_in_1_cluster <- gene_counts %>%
  filter(n_clusters == 1)

# Genes present in two genetic clusters
genes_in_2_clusters <- gene_counts %>%
  filter(n_clusters == 2)

# Genes present in three genetic clusters
genes_in_3_clusters <- gene_counts %>%
  filter(n_clusters == 3)

# Genes present in four genetic clusters
genes_in_4_clusters <- gene_counts %>%
  filter(n_clusters == 4)

# Genes present in five genetic clusters
genes_in_5_clusters <- gene_counts %>%
  filter(n_clusters == 5)

# Genes present in six genetic clusters
genes_in_6_clusters <- gene_counts %>%
  filter(n_clusters == 6)

# print gene-distribution results
genes_in_1_cluster
genes_in_2_clusters
genes_in_3_clusters
genes_in_4_clusters
genes_in_5_clusters
genes_in_6_clusters

# save gene-distribution table
write.csv(
  gene_counts,
  file.path(
    output_dir,
    "gene_cluster_distribution.csv"
  ),
  row.names = FALSE
)


##### filter genes for visualization #####

# Keep genes with alternate allele frequency >= 0.20
# in at least one genetic cluster.
genes_keep <- plot_df %>%
  filter(!is.na(gene_label)) %>%
  group_by(gene_label) %>%
  summarise(
    max_alt_freq = max(
      alt_freq,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) %>%
  filter(
    max_alt_freq >= 0.20
  ) %>%
  pull(gene_label)


plot_df_filtered <- plot_df %>%
  filter(
    gene_label %in% genes_keep
  )

# preserve gene order after filtering
plot_df_filtered$gene_label <- factor(
  plot_df_filtered$gene_label,
  levels = levels(plot_df$gene_label)
)


##### plot alternate allele frequencies #####

p_gene <- ggplot(
  plot_df_filtered,
  aes(
    x = gene_label,
    y = alt_freq,
    fill = cluster
  )
) +
  geom_col() +
  
  facet_wrap(
    ~ cluster,
    ncol = 1
  ) +
  
  scale_fill_manual(
    values = cluster_colors,
    name = "Genetic Cluster"
  ) +
  
  coord_cartesian(
    ylim = c(0, 1)
  ) +
  
  labs(
    x = "Gene symbol",
    y = "Alternate allele frequency"
  ) +
  
  theme_bw() +
  
  theme(
    panel.grid = element_blank(),
    
    axis.title = element_text(
      size = 14
    ),
    
    axis.text.x = element_text(
      size = 12,
      angle = 90,
      hjust = 1,
      vjust = 0.5
    ),
    
    axis.text.y = element_text(
      size = 10
    ),
    
    strip.text = element_text(
      size = 14,
      face = "bold"
    ),
    
    legend.title = element_text(
      size = 14
    ),
    
    legend.text = element_text(
      size = 12
    )
  )

p_gene

##### save alternate allele-frequency plot #####

# PNG
ggsave(
  file.path(
    output_dir,
    "gene_frequency_plot.png"
  ),
  plot = p_gene,
  width = 8.27,
  height = 11.69,
  units = "in",
  dpi = 600
)


# PDF
ggsave(
  file.path(
    output_dir,
    "gene_frequency_plot.pdf"
  ),
  plot = p_gene,
  width = 8.27,
  height = 11.69,
  units = "in"
)


# SVG
ggsave(
  file.path(
    output_dir,
    "gene_frequency_plot.svg"
  ),
  plot = p_gene,
  width = 8.27,
  height = 11.69,
  units = "in"
)