# load libraries
library(ggplot2) # plotting
library(dplyr)   # data manipulation and dataframe processing

# set paths
data_dir <- "r_data"
output_dir <- "r_results"

# creates r_results folder if it does not exist
dir.create(output_dir, showWarnings = FALSE)

# load SNP density data generated by vcftools
snp_density <- read.table(
  file.path(data_dir, "snp_density.snpden"),
  header = TRUE
)

##### summary statistics #####

# mean SNP density
mean_density <- mean(snp_density$VARIANTS.KB)

# standard deviation
sd_density <- sd(snp_density$VARIANTS.KB)

# median SNP density
median_density <- median(snp_density$VARIANTS.KB)

# print summary statistics
mean_density
sd_density
median_density

##### SNP density distribution #####

density_plot <- ggplot(
  snp_density,
  aes(x = VARIANTS.KB)
) +
  geom_density(
    color = "black",
    linewidth = 0.5
  ) +
  geom_vline(
    xintercept = mean_density,
    color = "blue",
    linetype = "dashed",
    linewidth = 0.8
  ) +
  scale_x_continuous(
    limits = c(0, 10),
    breaks = c(0, 2, 4, 6, 8, 10),
    expand = c(0, 0)
  ) +
  labs(
    x = "Variants/kB",
    y = "Density"
  ) +
  theme_classic() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.5
    )
  )
# save PNG
ggsave(
  file.path(output_dir, "snp_density_distribution.png"),
  plot = density_plot,
  width = 8,
  height = 6,
  dpi = 600
)

##### genome-wide SNP density plot #####

# calculate chromosome lengths
chr_lengths <- snp_density %>%
  group_by(CHROM) %>%
  summarize(
    chr_len = max(BIN_START)
  ) %>%
  arrange(
    factor(CHROM, levels = unique(snp_density$CHROM))
  )

# calculate cumulative chromosome positions
chr_lengths <- chr_lengths %>%
  mutate(
    chr_start = lag(
      cumsum(chr_len),
      default = 0
    )
  )

# merge chromosome offsets
snpden_cum <- snp_density %>%
  left_join(chr_lengths, by = "CHROM") %>%
  mutate(
    genome_pos = BIN_START + chr_start
  )

# plot
genome_plot <- ggplot(
  snpden_cum,
  aes(
    x = genome_pos / 1000000,
    y = VARIANTS.KB
  )
) +
  geom_point(
    size = 0.5,
    alpha = 0.5
  ) +
  geom_smooth(
    span = 0.1,
    se = FALSE,
    color = "blue"
  ) +
  labs(
    # title = "SNP Density Across the Genome",
    x = "Genome Position (Mb)",
    y = "Variants per KB"
  ) +
  theme_minimal()

# save PNG
ggsave(
  file.path(output_dir, "genome_snp_density.png"),
  plot = genome_plot,
  width = 10,
  height = 6,
  dpi = 600
)
