library(dplyr)      # data manipulation and dataframe processing
library(vegan)      # Mantel test for correlation between distance matrices
library(geosphere)  # calculation of geographic distances from coordinates

### set paths ###

# directory containing FST results generated by fst.R
results_dir <- "r_results"

# directory containing sampling-site coordinate data
data_dir <- "r_data"

# read pairwise FST results generated by fst_analysis.R
fst_table <- read.csv(
  file.path(results_dir, "pairwise_fst_summary.csv")
) %>%
  select(
    Pop1,
    Pop2,
    Weighted_FST
  )

# Create pairwise FST matrix
populations <- unique(
  c(
    fst_table$Pop1,
    fst_table$Pop2
  )
)

fst_matrix <- matrix(
  0,
  nrow = length(populations),
  ncol = length(populations),
  dimnames = list(
    populations,
    populations
  )
)

# fill both halves of the symmetric matrix
for (i in seq_len(nrow(fst_table))) {
  pop1 <- fst_table$Pop1[i]
  pop2 <- fst_table$Pop2[i]
  fst <- fst_table$Weighted_FST[i]
  
  fst_matrix[pop1, pop2] <- fst
  fst_matrix[pop2, pop1] <- fst
}

# calculate genetic distance
# transform pairwise FST to FST / (1 - FST)
genetic_dist_matrix <- fst_matrix / (1 - fst_matrix)
genetic_dist <- as.dist(genetic_dist_matrix)

# read sampling coordinates
coordinates <- read.csv(file.path(data_dir, "coordinates.csv"))

# calculate mean coordinates for each genetic cluster
cluster_coords <- coordinates %>%
  group_by(Cluster) %>%
  summarise(
    lat = mean(LatY, na.rm = TRUE),
    lon = mean(LatX, na.rm = TRUE),
    .groups = "drop"
  )

# match population order between genetic and geographic data
cluster_coords <- cluster_coords %>%
  filter(Cluster %in% populations) %>%
  arrange(
    match(Cluster, populations)
  )

# calculate geographic distances
geo_dist_matrix <- distm(
  cluster_coords[, c("lon", "lat")],
  fun = distHaversine
)

# convert meters to kilometers
geo_dist_matrix <- geo_dist_matrix / 1000
geo_dist <- as.dist(geo_dist_matrix)

# Mantel test
mantel_result <- mantel(
  genetic_dist,
  geo_dist,
  method = "pearson",
  permutations = 9999
)

print(mantel_result)

# save Mantel test results
mantel_summary <- data.frame(
  mantel_r = unname(mantel_result$statistic),
  p_value = mantel_result$signif,
  permutations = mantel_result$permutations
)

write.csv(
  mantel_summary,
  file.path(results_dir, "mantel_test_results.csv"),
  row.names = FALSE
)
